#!/bin/bash
(set -o igncr) &>/dev/null && set -o igncr && export SHELLOPTS # ignore cr
# Avoid recursion on scripts called from ~/.bashrc
unset BASH_ENV
for f in \
    ~/.pre_bivio_bashrc \
    ~/.pre.bashrc \
    /etc/bashrc \
    ~/src/*/home-env/bashrc.d/*.sh \
    ~/.post.bashrc \
    ~/.post_bivio_bashrc \
    ; do
    test -f $f && . $f
done
unset f
